name = "statuspage"
main = "src/index.ts"
compatibility_date = "2025-03-16"

[observability]
enabled = true

[dev]
port = 8788

[[kv_namespaces]]
binding = "STATUS_HISTORY"
id = "8ded4d8e6c6045a68c6cb8d76137df62"
