name = "statuspage"
main = "src/index.ts"
compatibility_date = "2025-03-16"

[observability]
enabled = true

[dev]
port = 8788

[[kv_namespaces]]
binding = "STATUS_HISTORY"
id = "80e2c1af6de14efba5d68e03e1f71f28"
